package com.fraudmanager.rules.computes;

import com.fraudmanager.flink.model.Measurment;
import ma.s2m.auth.ITransaction;
import com.fraudmanager.flink.utils.TimeConversion;
import org.apache.flink.streaming.api.windowing.time.Time;
import com.fraudmanager.flink.model.ExternalSystem;
import java.util.List;
import java.util.Arrays;
import java.time.Duration;
import java.time.LocalDate;
import com.fraudmanager.flink.utils.Utils;
import com.fraudmanager.flink.model.computation.MeasurmentRecord;
import com.fraudmanager.flink.model.computation.RecordHashMap;
import com.fraudmanager.flink.model.computation.Subject;
import ma.s2m.auth.Alert;
import ma.medtech.droolbuilder.messaging.IMessageSender;
import ma.medtech.droolbuilder.services.TypeConverter;

global TimeConversion timeConverter;
global ExternalSystem externalSystem;
global IMessageSender messageSender;
global TypeConverter typeConverter;

rule "(Rule Type COMPUTE) compute : repeated transactions at the same merchant"
no-loop true
lock-on-active true
salience 1000
agenda-group "Merchant->10 seconds"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R001"), $merchant: transaction.merchant, transaction.merchant==$merchant, transaction.autTranCode=="7001", transaction.autMercTypeF018=="7011", transaction.autPaymChan=="5", transaction.autCardEntrCapaF22_01=="3", transaction.autRespCodeF039=="000")
then
$record.setCount($record.getCount() + 1);
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL_R001", $record);;
update($measurment);
end

rule "(Rule Type ALERT) alert: repeated transactions at the same merchant"
no-loop true

salience 200
agenda-group "Merchant->10 seconds"
when
$measurment: Measurment($merchant: transaction.merchant, $record: records.get("COUNT_OF_TRANSACTION_ALL_R001"), $record.count>=3L)
then
messageSender.send("Alert: More than 3L transactions done with the same merchant with TranCode=7001, MCC=7011, Support=Contactless " + $merchant + " within 10 second(s)",Alert.POSITIVE);
update($measurment);
end


