package com.fraudmanager.rules.computes;

import com.fraudmanager.flink.model.Measurment;
import ma.s2m.auth.ITransaction;
import com.fraudmanager.flink.utils.TimeConversion;
import org.apache.flink.streaming.api.windowing.time.Time;
import com.fraudmanager.flink.model.ExternalSystem;
import java.util.List;
import java.util.Arrays;
import java.time.Duration;
import java.time.LocalDate;
import com.fraudmanager.flink.utils.Utils;
import com.fraudmanager.flink.model.computation.MeasurmentRecord;
import com.fraudmanager.flink.model.computation.RecordHashMap;
import com.fraudmanager.flink.model.computation.Subject;
import ma.s2m.auth.Alert;
import ma.medtech.droolbuilder.messaging.IMessageSender;
import ma.medtech.droolbuilder.services.TypeConverter;

global TimeConversion timeConverter;
global ExternalSystem externalSystem;
global IMessageSender messageSender;
global TypeConverter typeConverter;

rule "(Rule Type COMPUTE) COMPUTE More than 70 transactions of type 7000 (Cash Disbursement ATM)  at MCC 3604 (Hilton Garden Inn) in Iraq (999) with Boliviano (068) using Contactless within 1 minute."
no-loop true
lock-on-active true
salience 1000
agenda-group "Merchant->1 minute"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R006"), $merchant: transaction.merchant, transaction.merchant==$merchant, transaction.autTranCode=="7000", transaction.autMercTypeF018=="3604", transaction.autAcqrInstCounCodeF019=="999", transaction.autTranCurrF049=="068", transaction.autCardEntrCapaF22_01=="3", transaction.autRespCodeF039=="000")
then
$record.setCount($record.getCount() + 1);
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL_R006", $record);;
update($measurment);
end

rule "(Rule Type COMPUTE) compute : repeated transactions at the same merchant"
no-loop true
lock-on-active true
salience 1000
agenda-group "Merchant->10 seconds"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R001"), $merchant: transaction.merchant, transaction.merchant==$merchant, transaction.autTranCode=="7001", transaction.autMercTypeF018=="7011", transaction.autPaymChan=="5", transaction.autCardEntrCapaF22_01=="3", transaction.autRespCodeF039=="000")
then
$record.setCount($record.getCount() + 1);
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL_R001", $record);;
update($measurment);
end

rule "(Rule Type COMPUTE) Compute number of transactions within 1 minute(s)"
no-loop true
lock-on-active true
salience 1000
agenda-group "Card->1 minute"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL"))
then
$record.getCount() = $record.getCount()+1L;
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL", $record);
;
update($measurment);
end

rule "(Rule Type ALERT) ALERT More than 70 transactions of type 7000 (Cash Disbursement ATM)  at MCC 3604 (Hilton Garden Inn) in Iraq (999) with Boliviano (068) using Contactless within 1 minute."
no-loop true

salience 200
agenda-group "Merchant->1 minute"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R006"), $merchant: transaction.merchant, $record.count>=70L)
then
messageSender.send("Alert: More than 70L transactions detected at " + $merchant + ", TranCode=7000, MCC=3604 (Hilton Garden Inn), Country=Iraq (999), Currency=Boliviano (068), Support=Contactless within 1 minute(s)",Alert.POSITIVE);
update($measurment);
end

rule "(Rule Type COMPUTE) COMPUTE More than 40 transactions of type 21013 (Account Transfer) at  MCC 3177 (Airtan Airways) in Bangladesh (050) using Contactless within 1 month."
no-loop true
lock-on-active true
salience 1000
agenda-group "Merchant->1 month"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R005"), $merchant: transaction.merchant, transaction.merchant==$merchant, transaction.autTranCode=="21013", transaction.autMercTypeF018=="3177", transaction.autAcqrInstCounCodeF019=="050", transaction.autCardEntrCapaF22_01=="3", transaction.autRespCodeF039=="000")
then
$record.setCount($record.getCount() + 1);
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL_R005", $record);;
update($measurment);
end

rule "(Rule Type ALERT) ALERT More than 30 transactions of type 7006 (Cash Out) at MCC  7993 (Video Amusement Game) in Jordan (400) with Iraqi Dinar (368) using Piste within 1 week."
no-loop true

salience 200
agenda-group "Merchant->7 days"
when
$measurment: Measurment($merchant: transaction.merchant, $record: records.get("COUNT_OF_TRANSACTION_ALL_R004"), $record.count>=30L)
then
messageSender.send("Alert: More than 30L transactions of type 41000 (Smart Cash Deposit) at MCC=3543 (Four Seasons) using Puce at the same merchant " + $merchant + " within 7 day(s)",Alert.POSITIVE);
update($measurment);
end

rule "(Rule Type COMPUTE) R000: COMPUTE More than 20 transactions of type 5000 (Sales Draft) at MCC 3641 (Sofitel Hotels) in Morocco (504) with Moroccan Dirham (504) using Puce within 1 hour"
no-loop true
lock-on-active true
salience 1000
agenda-group "Merchant->1 hour"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R000"), $merchant: transaction.merchant, transaction.merchant==$merchant, transaction.autTranCode=="5000", transaction.autMercTypeF018=="3641", transaction.autAcqrInstCounCodeF019=="504", transaction.autTranCurrF049=="504", transaction.autCardEntrCapaF22_01=="1", transaction.autRespCodeF039=="000")
then
$record.setCount($record.getCount() + 1);
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL_R000", $record);;
update($measurment);
end

rule "(Rule Type ALERT) R009 ALERT More than 10 transactions > 15,000 MAD at the same merchant within 1 week."
no-loop true

salience 200
agenda-group "Merchant->7 days"
when
$measurment: Measurment($merchant: transaction.merchant, $record: records.get("COUNT_OF_TRANSACTION_ALL_R009"), $record.count>=10L)
then
messageSender.send("Alert: More than 10L transactions greater than 15,000 MAD at the same merchant " + $merchant + " within 7 day(s)",Alert.POSITIVE);
update($measurment);
end

rule "(Rule Type COMPUTE) compute : repeated transactions at the same merchant"
no-loop true
lock-on-active true
salience 1000
agenda-group "Merchant->10 seconds"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R001"), $merchant: transaction.merchant, transaction.merchant==$merchant, transaction.autTranCode=="7001", transaction.autMercTypeF018=="7011", transaction.autPaymChan=="5", transaction.autCardEntrCapaF22_01=="3", transaction.autRespCodeF039=="000")
then
$record.setCount($record.getCount() + 1);
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL_R001", $record);;
update($measurment);
end

rule "(Rule Type COMPUTE) R008 COMPUTE More than 50 transactions of type 7007 (Salary Withdrawal POS)  at MCC 3260 (Spirit Air) in United Arab Emirates (466) with Afghani Lek (004) using Puce within 3 months."
no-loop true
lock-on-active true
salience 1000
agenda-group "Merchant->3 months"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R008"), $merchant: transaction.merchant, transaction.merchant==$merchant, transaction.autTranCode=="7007", transaction.autMercTypeF018=="3260", transaction.autAcqrInstCounCodeF019=="466", transaction.autTranCurrF049=="004", transaction.autCardEntrCapaF22_01=="1", transaction.autRespCodeF039=="000")
then
$record.setCount($record.getCount() + 1);
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL_R008", $record);;
update($measurment);
end

rule "(Rule Type ALERT) ALERTMore than 20 transactions of type 5000 (Sales Draft) at MCC 3641 (Sofitel Hotels) in Morocco (504) with Moroccan Dirham (504) using Puce within 1 hour"
no-loop true

salience 200
agenda-group "Merchant->1 hour"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R000"), $merchant: transaction.merchant, $record.count>=20L)
then
Alert alert = new Alert("Alert: More than 20L transactions detected at merchant " + $merchant + ",TranCode=5000, MCC=3641 (Sofitel), Country=Morocco (504), Currency=MAD (504), Support=Puce within 1 hour(s)",Alert.POSITIVE);
alert.setWeight(100);;
alert.setRuleTitle("ALERTMore than 20 transactions of type 5000 (Sales Draft) at MCC 3641 (Sofitel Hotels) in Morocco (504) with Moroccan Dirham (504) using Puce within 1 hour");;
alert.setTotalAmount($record.getAmount());
alert.setTotalCount($record.getCount());
$measurment.getAlertSet().addAlert(alert);;
update($measurment);
end

rule "(Rule Type COMPUTE) COMPUTE NUMBER OF TRANSACTIONS WITH THE SAME MERCHANT WITHIN 1 hour(s)"
no-loop true
lock-on-active true
salience 1000
agenda-group "Card->1 hour"
when
$measurment: Measurment($merchant: transaction.merchant)
    
    eval($merchant != null)
    $key0: String() from "COUNT".concat("_OF").concat("_TRANSACTION").concat("_ALL").concat("_").concat($merchant.toString())
    $record: MeasurmentRecord() from $measurment.getRecords().get($key0)
    Measurment()
then
$record.setCount($record.getCount() + 1);
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL_" + $merchant, $record);;
update($measurment);
end

rule "(Rule Type ALERT) ALERT More than 40 transactions of type 21013 (Account Transfer) at  MCC 3177 (Airtan Airways) in Bangladesh (050) using Contactless within 1 month."
no-loop true

salience 200
agenda-group "Merchant->1 month"
when
$measurment: Measurment($merchant: transaction.merchant, $record: records.get("COUNT_OF_TRANSACTION_ALL_R005"), $record.count>=40L)
then
Alert alert = new Alert("Alert: More than 40L transactions of type 21013 (Account Transfer) at MCC=3177 (Airtan Airways) in Bangladesh using Contactless at the same merchant " + $merchant + " within 1 month(s)",Alert.POSITIVE);
alert.setWeight(100);;
alert.setRuleTitle("ALERT More than 40 transactions of type 21013 (Account Transfer) at  MCC 3177 (Airtan Airways) in Bangladesh (050) using Contactless within 1 month.");;
alert.setTotalAmount($record.getAmount());
alert.setTotalCount($record.getCount());
$measurment.getAlertSet().addAlert(alert);;
update($measurment);
end

rule "(Rule Type ALERT) ALERTMore than 20 transactions of type 5000 (Sales Draft) at MCC 3641 (Sofitel Hotels) in Morocco (504) with Moroccan Dirham (504) using Puce within 1 hour"
no-loop true

salience 200
agenda-group "Merchant->1 hour"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R000"), $merchant: transaction.merchant, $record.count>=20L)
then
Alert alert = new Alert("Alert: More than 20L transactions detected at merchant " + $merchant + ",TranCode=5000, MCC=3641 (Sofitel), Country=Morocco (504), Currency=MAD (504), Support=Puce within 1 hour(s)",Alert.POSITIVE);
alert.setWeight(100);;
alert.setRuleTitle("ALERTMore than 20 transactions of type 5000 (Sales Draft) at MCC 3641 (Sofitel Hotels) in Morocco (504) with Moroccan Dirham (504) using Puce within 1 hour");;
alert.setTotalAmount($record.getAmount());
alert.setTotalCount($record.getCount());
$measurment.getAlertSet().addAlert(alert);;
update($measurment);
end

rule "(Rule Type COMPUTE) R009 COMPUTE More than 10 transactions > 15,000 MAD at the same merchant within 1 week."
no-loop true
lock-on-active true
salience 1000
agenda-group "Merchant->7 days"
when
$measurment: Measurment($merchant: transaction.merchant, $amount: transaction.amount, $record: records.get("COUNT_OF_TRANSACTION_ALL_R009"), transaction.merchant==$merchant, transaction.autTranCurrF049=="504", transaction.amount>15000L, transaction.autRespCodeF039=="000")
then
$record.setCount($record.getCount() + 1);
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL_R009", $record);;
update($measurment);
end

rule "(Rule Type ALERT) R008 ALERTMore than 50 transactions of type 7007 (Salary Withdrawal POS)  at MCC 3260 (Spirit Air) in United Arab Emirates (466) with Afghani Lek (004) using Puce within 3 months."
no-loop true

salience 200
agenda-group "Merchant->3 months"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R008"), $merchant: transaction.merchant, $record.count>=50L)
then
messageSender.send("Alert: More than 50L transactions detected at " + $merchant + ", TranCode=7007, MCC=3260 (Spirit Air), Country=UAE (466), Currency=Afghani Lek (004), Support=Puce within 3 month(s)",Alert.POSITIVE);
update($measurment);
end

rule "(Rule Type ALERT) R007 COMPUTE More than 100 transactions of type 5000 (Sales Draft) at MCC  3519 (Pullman International Hotels) in Kazakhstan (398) with Jamaican Dollar (388) using Puce within 24 hours."
no-loop true

salience 200
agenda-group "Merchant->1 day"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R007"), $merchant: transaction.merchant, transaction.merchant==$merchant, transaction.autTranCode=="5000", transaction.autMercTypeF018=="3519", transaction.autAcqrInstCounCodeF019=="398", transaction.autTranCurrF049=="388", transaction.autCardEntrCapaF22_01=="1", transaction.autRespCodeF039=="000")
then
$record.setCount($record.getCount() + 1);
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL_R007", $record);;
update($measurment);
end

rule "(Rule Type COMPUTE) COMPUTE More than 30 transactions of type 7006 (Cash Out) at MCC  7993 (Video Amusement Game) in Jordan (400) with Iraqi Dinar (368) using Piste within 1 week."
no-loop true
lock-on-active true
salience 1000
agenda-group "Merchant->7 days"
when
$measurment: Measurment($merchant: transaction.merchant, $record: records.get("COUNT_OF_TRANSACTION_ALL_R004"), $record.count>=30L)
then
messageSender.send("Alert: More than 30L transactions of type 5000 (Sales Draft) at MCC=3641 in Morocco with MAD using Puce at the same merchant " + $merchant + " within 7 day(s)",Alert.POSITIVE);
update($measurment);
end

rule "(Rule Type ALERT) Alert if the number of transactions exceeds 10L whithin 1 minute(s)"
no-loop true

salience 200
agenda-group "Card->1 minute"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL"), $record.count>=10L)
then
Alert alert = new Alert("Alert: the number of transactions exceeded 10L within 1 minute(s)",Alert.POSITIVE);
alert.setWeight(100);;
alert.setRuleTitle("Alert if the number of transactions exceeds 10L whithin 1 minute(s)");;
alert.setTotalAmount($record.getAmount());
alert.setTotalCount($record.getCount());
$measurment.getAlertSet().addAlert(alert);;
update($measurment);
end

rule "(Rule Type ALERT) ALERT IF MORE THAN 15 CASH DISBURSEMENT ATM TRANSACTIONS (7000) AT MCC 6011 USING PISTE WITH SAME MERCHANT WITHIN 15 MINUTES"
no-loop true

salience 200
agenda-group "Merchant->15 minutes"
when
$measurment: Measurment($merchant: transaction.merchant, $record: records.get("COUNT_OF_TRANSACTION_ALL_R002"), $record.count>=15L)
then
messageSender.send("Alert: More than 15L transactions of type 7000 (Cash Disbursement ATM) at MCC 6011 (Financial Institution ATM) using Piste done with the same merchant within 15 minute(s)",Alert.POSITIVE);
update($measurment);
end

rule "(Rule Type COMPUTE) COMPUTE TOTAL NUMBER OF 7000 CASH DISBURSEMENT ATM TRANSACTIONS AT MCC 6011 USING PISTE PER MERCHANT IN 15 minute(s)"
no-loop true
lock-on-active true
salience 1000
agenda-group "Card->15 minutes"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R002"), $merchant: transaction.merchant, transaction.merchant==$merchant, transaction.autTranCode=="7000", transaction.autMercTypeF018=="6011", transaction.autCardEntrCapaF22_01=="2", transaction.autRespCodeF039=="000")
then
$record.setCount($record.getCount() + 1);
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL_R002", $record);;
update($measurment);
end

rule "(Rule Type ALERT) ALERT IF TOTAL NUMBER OF INVALID PIN ATTEMPTS EXCEEDS 5L IN 1 minute(s) PERIOD"
no-loop true

salience 200
agenda-group "Card->1 minute"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_INVALIDPIN_ATTEMPTS"), $record.count>=5L)
then
Alert alert = new Alert("Number of invalid PIN attempts exceeded 5L in 1 minute(s)",Alert.POSITIVE);
alert.setWeight(100);;
alert.setRuleTitle("ALERT IF TOTAL NUMBER OF INVALID PIN ATTEMPTS EXCEEDS 5L IN 1 minute(s) PERIOD");;
alert.setTotalAmount($record.getAmount());
alert.setTotalCount($record.getCount());
$measurment.getAlertSet().addAlert(alert);;
update($measurment);
end

rule "(Rule Type ALERT) ALERT More than 25 transactions of type 41000 (Smart Cash Deposit)  at MCC 3543 (Four Seasons) using Puce within 1 day."
no-loop true

salience 200
agenda-group "Merchant->1 day"
when
$measurment: Measurment($merchant: transaction.merchant, $record: records.get("COUNT_OF_TRANSACTION_ALL_R003"), $record.count>=25L)
then
messageSender.send("Alert: More than 25L transactions of type 5000 (Sales Draft) at MCC=3641 in Morocco with MAD using Puce at the same merchant " + $merchant + " within 1 day(s)",Alert.POSITIVE);
update($measurment);
end

rule "(Rule Type COMPUTE) COMPUTE More than 25 transactions of type 41000 (Smart Cash Deposit)  at MCC 3543 (Four Seasons) using Puce within 1 day"
no-loop true
lock-on-active true
salience 1000
agenda-group "Merchant->1 day"
when
$measurment: Measurment($merchant: transaction.merchant, $record: records.get("COUNT_OF_TRANSACTION_ALL_R003"), transaction.merchant==$merchant, transaction.autTranCode=="5000", transaction.autMercTypeF018=="3641", transaction.autCardEntrCapaF22_01=="1", transaction.autRespCodeF039=="000", transaction.autAcqrInstCounCodeF019=="504", transaction.autTranCurrF049=="504")
then
$record.setCount($record.getCount() + 1);
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL_R003", $record);;
update($measurment);
end

rule "(Rule Type ALERT) alert: repeated transactions at the same merchant"
no-loop true

salience 200
agenda-group "Merchant->10 seconds"
when
$measurment: Measurment($merchant: transaction.merchant, $record: records.get("COUNT_OF_TRANSACTION_ALL_R001"), $record.count>=3L)
then
messageSender.send("Alert: More than 3L transactions done with the same merchant with TranCode=7001, MCC=7011, Support=Contactless " + $merchant + " within 10 second(s)",Alert.POSITIVE);
update($measurment);
end

rule "(Rule Type ALERT) R007 ALERT More than 100 transactions of type 5000 (Sales Draft) at MCC  3519 (Pullman International Hotels) in Kazakhstan (398) with Jamaican Dollar (388) using Puce within 24 hours."
no-loop true

salience 200
agenda-group "Merchant->1 day"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL_R007"), $merchant: transaction.merchant, $record.count>=100L)
then
messageSender.send("Alert: More than 100L transactions of type 5000 (Sales Draft) at MCC=3519 (Pullman International Hotels) in Kazakhstan with Jamaican Dollar using Puce at the same merchant " + $merchant + " within 1 day(s)",Alert.POSITIVE);
update($measurment);
end


