package com.fraudmanager.rules.computes;

import com.fraudmanager.flink.model.Measurment;
import ma.s2m.auth.ITransaction;
import com.fraudmanager.flink.utils.TimeConversion;
import org.apache.flink.streaming.api.windowing.time.Time;
import com.fraudmanager.flink.model.ExternalSystem;
import java.util.List;
import java.util.Arrays;
import java.time.Duration;
import java.time.LocalDate;
import com.fraudmanager.flink.utils.Utils;
import com.fraudmanager.flink.model.computation.MeasurmentRecord;
import com.fraudmanager.flink.model.computation.RecordHashMap;
import com.fraudmanager.flink.model.computation.Subject;
import ma.s2m.auth.Alert;
import ma.medtech.droolbuilder.messaging.IMessageSender;
import ma.medtech.droolbuilder.services.TypeConverter;

global TimeConversion timeConverter;
global ExternalSystem externalSystem;
global IMessageSender messageSender;
global TypeConverter typeConverter;

rule "(Rule Type COMPUTE) Compute number of transactions within 1 minute(s)"
no-loop true
lock-on-active true
salience 1000
agenda-group "Card->1 minute"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL"))
then
$record.getCount() = $record.getCount()+1L;
$measurment.getRecords().put("COUNT_OF_TRANSACTION_ALL", $record);
;
update($measurment);
end

rule "(Rule Type ALERT) Alert if the number of transactions exceeds 10L whithin 1 minute(s)"
no-loop true

salience 200
agenda-group "Card->1 minute"
when
$measurment: Measurment($record: records.get("COUNT_OF_TRANSACTION_ALL"), $record.count>=10L)
then
Alert alert = new Alert("Alert: the number of transactions exceeded 10L within 1 minute(s)",Alert.POSITIVE);
alert.setWeight(100);;
alert.setRuleTitle("Alert if the number of transactions exceeds 10L whithin 1 minute(s)");;
alert.setTotalAmount($record.getAmount());
alert.setTotalCount($record.getCount());
$measurment.getAlertSet().addAlert(alert);;
update($measurment);
end

rule "(Rule Type COMPUTE) Compute total amount of trx within 1 hour(s)"
no-loop true
lock-on-active true
salience 1000
agenda-group "Card->1 hour"
when
$measurment: Measurment($record: records.get("AMOUNT_OF_TRANSACTION_ALL"))
then
$record.setAmount($record.getAmount() + $measurment.getTransaction().getAmount());
$measurment.getRecords().put("AMOUNT_OF_TRANSACTION_ALL", $record);;
update($measurment);
end

rule "(Rule Type ALERT) Alert if total amount of trx within 1 hour(s) exceeds 10000.0"
no-loop true

salience 200
agenda-group "Card->1 hour"
when
$measurment: Measurment($record: records.get("AMOUNT_OF_TRANSACTION_ALL"), $record.amount>=10000.0)
then
Alert alert = new Alert("Alert: Total amount of trx within 1 hour(s) exceeded 10000.0",Alert.POSITIVE);
alert.setWeight(100);;
alert.setRuleTitle("Alert if total amount of trx within 1 hour(s) exceeds 10000.0");;
alert.setTotalAmount($record.getAmount());
alert.setTotalCount($record.getCount());
$measurment.getAlertSet().addAlert(alert);;
update($measurment);
end


